version: "3.9"
services:
  server:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
  db:
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password