# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@1.0.4
      with:
        docker_version: "20.10"
        docker_channel: stable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run static code checks
      run: ./gradlew detekt
    - name: Build and run tests with Gradle
      run: ./gradlew clean build
    - name: Run integration tests with Gradle
      run: ./gradlew integrationTest
